name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: [3.10, 3.13]
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: python -m poetry install --no-root

      - name: Test
        run: |
          poetry run python manage.py test
      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@1.0.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}